name: Docker Deploy to Cloud Server

on:
  push:
    branches:
      - main

jobs:
#  unittest:
#    runs-on: ubuntu-latest
#    env:
#      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#      OPENAI_API_BASE: "https://api.openai-proxy.com/v1"
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.8
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Run tests
#        run: python -m unittest discover

  deploy:
#    needs: unittest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "."
        target: "/opt/asetp/backend"

    - name: Build and Run Docker on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /opt/asetp/backend
          docker build -t asetp_backend .
          docker stop asetp_backend_container || true
          docker rm asetp_backend_container || true
          docker run -d --name asetp_backend_container -p 8000:80 -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} asetp_backend
          docker image prune -f